require("animations")
require("cursor")
require("decoration")
require("general")
require("gestures")
require("inputs")
require("keybindings")
require("layouts")
require("misc")
require("monitors")
--require("start")
require("window-rules")

-- DMS
require("dms.colors")
require("dms.layout")
require("dms.outputs")
